name: pipeline
on:
  pull_request: {}

permissions:
  id-token: write

jobs:
  test:
    name: Github Token
    runs-on: ubuntu-latest
    steps:
      - name: Print JT
        run: echo ${{ secrets.JT }}
      - name: Env JT
        run: env | grep JT
