name: pipeline
on:
  pull_request: {}

permissions:
  id-token: write

jobs:
  test:
    name: Github Token
    runs-on: ubuntu-latest
    steps:
      - name: Set GITHUB_TOKEN
        run: export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
      - name: Print env
        run: env | grep -i token
      - name: Print GITHUB_TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}
